name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: @s0fttsp
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            I will build now
